# Generated by Django 5.0.6 on 2024-08-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcour",
            name="entreprise",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="entreprise"
            ),
        ),
        migrations.AddField(
            model_name="parcour",
            name="pays",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="ville"
            ),
        ),
        migrations.AddField(
            model_name="parcour",
            name="type",
            field=models.CharField(
                choices=[("cdi", "CDI"), ("cdd", "CDD"), ("stage", "STAGE")],
                default="",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parcour",
            name="ville",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="ville"
            ),
        ),
        migrations.AlterField(
            model_name="parcour",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
