# Generated by Django 5.0.6 on 2024-08-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portfolio", "0002_parcour_entreprise_parcour_pays_parcour_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcour",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="parcour",
            name="pays",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Pays"
            ),
        ),
        migrations.AlterField(
            model_name="parcour",
            name="ville",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Ville"
            ),
        ),
    ]
