# Generated by Django 5.0.6 on 2024-08-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portfolio", "0003_parcour_created_at_alter_parcour_pays_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcour",
            name="pays",
            field=models.CharField(max_length=255, null=True, verbose_name="Pays"),
        ),
        migrations.AlterField(
            model_name="parcour",
            name="ville",
            field=models.CharField(max_length=255, null=True, verbose_name="Ville"),
        ),
    ]
