# Generated by Django 5.0.6 on 2024-08-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portfolio", "0004_alter_parcour_pays_alter_parcour_ville"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcour",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Titre"),
        ),
    ]
