# Generated by Django 5.0.6 on 2024-08-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portfolio", "0005_alter_parcour_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcour",
            name="entreprise",
            field=models.CharField(
                max_length=255, null=True, verbose_name="entreprise"
            ),
        ),
    ]
