# Generated by Django 5.0.6 on 2024-09-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portfolio", "0006_alter_parcour_entreprise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcour",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="parcour",
            name="type",
            field=models.CharField(
                choices=[
                    ("cdi", "CDI"),
                    ("cdd", "CDD"),
                    ("stage", "STAGE"),
                    ("formation", "FORMATION"),
                ],
                default="",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
