# Generated by Django 5.0.6 on 2024-09-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portfolio", "0007_alter_parcour_logo_alter_parcour_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcour",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="Parcours/"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Skills/"),
        ),
    ]
